/* discoverStub.h
   Generated by gSOAP 2.8.27 from onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_WSDD_2005
#define SOAP_WSA_200408
#define SOAP_NAMESPACE_OF_wsdd	"http://schemas.xmlsoap.org/ws/2005/04/discovery"
#define SOAP_NAMESPACE_OF_tdn	"http://www.onvif.org/ver10/network/wsdl"

#ifndef discoverStub_H
#define discoverStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20827
# error "GSOAP VERSION 20827 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/* wsa.h:119 */
#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
/* wsa:RelationshipTypeValues */
typedef enum wsa__RelationshipTypeValues
{
	wsa__Reply = 0
} wsa__RelationshipTypeValues;
#endif

/* wsa.h:127 */
#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
/* wsa:FaultSubcodeValues */
typedef enum wsa__FaultSubcodeValues
{
	wsa__InvalidMessageInformationHeader = 0,
	wsa__MessageInformationHeaderRequired = 1,
	wsa__DestinationUnreachable = 2,
	wsa__ActionNotSupported = 3,
	wsa__EndpointUnavailable = 4
} wsa__FaultSubcodeValues;
#endif

/* wsdd10.h:111 */
#ifndef SOAP_TYPE_wsdd__FaultCodeType
#define SOAP_TYPE_wsdd__FaultCodeType (58)
/* wsdd:FaultCodeType */
typedef enum wsdd__FaultCodeType
{
	wsdd__MatchingRuleNotSupported = 0
} wsdd__FaultCodeType;
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs, and Unions                                               *
 *                                                                            *
\******************************************************************************/

typedef struct wsa__EndpointReferenceType wsa__EndpointReferenceType;	/* wsa.h:94 */
typedef struct wsa__ReferencePropertiesType wsa__ReferencePropertiesType;	/* wsa.h:97 */
typedef struct wsa__ReferenceParametersType wsa__ReferenceParametersType;	/* wsa.h:100 */
typedef struct wsa__ServiceNameType wsa__ServiceNameType;	/* wsa.h:103 */
typedef struct wsa__Relationship wsa__Relationship;	/* wsa.h:106 */
typedef struct wsdd__HelloType wsdd__HelloType;	/* wsdd10.h:57 */
typedef struct wsdd__ByeType wsdd__ByeType;	/* wsdd10.h:60 */
typedef struct wsdd__ProbeType wsdd__ProbeType;	/* wsdd10.h:63 */
typedef struct wsdd__ProbeMatchesType wsdd__ProbeMatchesType;	/* wsdd10.h:66 */
typedef struct wsdd__ProbeMatchType wsdd__ProbeMatchType;	/* wsdd10.h:69 */
typedef struct wsdd__ResolveType wsdd__ResolveType;	/* wsdd10.h:72 */
typedef struct wsdd__ResolveMatchesType wsdd__ResolveMatchesType;	/* wsdd10.h:75 */
typedef struct wsdd__ResolveMatchType wsdd__ResolveMatchType;	/* wsdd10.h:78 */
typedef struct wsdd__SecurityType wsdd__SecurityType;	/* wsdd10.h:84 */
typedef struct wsdd__SigType wsdd__SigType;	/* wsdd10.h:87 */
typedef struct wsdd__ScopesType wsdd__ScopesType;	/* wsdd10.h:81 */
typedef struct wsdd__AppSequenceType wsdd__AppSequenceType;	/* wsdd10.h:90 */
struct __wsdd__Hello;	/* wsdx.h:67 */
struct __wsdd__Bye;	/* wsdx.h:76 */
struct __wsdd__Probe;	/* wsdx.h:85 */
struct __wsdd__ProbeMatches;	/* wsdx.h:94 */
struct __wsdd__Resolve;	/* wsdx.h:103 */
struct __wsdd__ResolveMatches;	/* wsdx.h:112 */
struct __tdn__Hello;	/* onvif.h:294 */
struct __tdn__Bye;	/* onvif.h:348 */
struct __tdn__Probe;	/* onvif.h:402 */

/* wsa.h:94 */
#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
/* wsa:EndpointReferenceType complex type: */
struct wsa__EndpointReferenceType
{
	char *Address;	/* required element of XSD type xsd:string */
	struct wsa__ReferencePropertiesType *ReferenceProperties;	/* optional element of XSD type wsa:ReferencePropertiesType */
	struct wsa__ReferenceParametersType *ReferenceParameters;	/* optional element of XSD type wsa:ReferenceParametersType */
	char **PortType;	/* optional element of XSD type xsd:QName */
	struct wsa__ServiceNameType *ServiceName;	/* optional element of XSD type wsa:ServiceNameType */
	int __size;	/* sequence of elements <-any> of XSD type xsd:anyType */
	char **__any;
	char *__anyAttribute;	/* optional attribute of XSD type xsd:anyType */
};
#endif

/* wsa.h:97 */
#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
/* wsa:ReferencePropertiesType complex type: */
struct wsa__ReferencePropertiesType
{
	int __size;	/* sequence of elements <-any> of XSD type xsd:anyType */
	char **__any;
};
#endif

/* wsa.h:100 */
#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
/* wsa:ReferenceParametersType complex type: */
struct wsa__ReferenceParametersType
{
	int __size;	/* sequence of elements <-any> of XSD type xsd:anyType */
	char **__any;
};
#endif

/* wsa.h:103 */
#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
/* wsa:ServiceNameType simple type: */
struct wsa__ServiceNameType
{
	char *__item;	/* mixed XML content */
	char *PortName;	/* optional attribute of XSD type xsd:string */
	char *__anyAttribute;	/* optional attribute of XSD type xsd:anyType */
};
#endif

/* wsa.h:106 */
#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
/* wsa:Relationship simple type: */
struct wsa__Relationship
{
	char *__item;	/* mixed XML content */
	char *RelationshipType;	/* optional attribute of XSD type xsd:QName */
	char *__anyAttribute;	/* optional attribute of XSD type xsd:anyType */
};
#endif

/* wsa.h:250 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *wsa__MessageID;	/* optional element of XSD type wsa:MessageID */
	struct wsa__Relationship *wsa__RelatesTo;	/* optional element of XSD type wsa:RelatesTo */
	struct wsa__EndpointReferenceType *wsa__From;	/* optional element of XSD type wsa:From */
	struct wsa__EndpointReferenceType *wsa__ReplyTo;	/* mustUnderstand */
	struct wsa__EndpointReferenceType *wsa__FaultTo;	/* mustUnderstand */
	char *wsa__To;	/* mustUnderstand */
	char *wsa__Action;	/* mustUnderstand */
	struct wsdd__AppSequenceType *wsdd__AppSequence;	/* optional element of XSD type wsdd:AppSequenceType */
};
#endif
#endif

/* wsa.h:266 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
/* SOAP-ENV:Detail complex type: */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below)
	   WARNING: do not create a cyclic data structure graph throught this element unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
	void *fault;	/* transient (not serialized) */
};
#endif
#endif

/* wsa.h:267 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
/* Type SOAP_ENV__Code is a recursive data type (in)directly referencing itself through its (base) class members */
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of XSD type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of XSD type SOAP-ENV:Code */
};
#endif
#endif

/* wsa.h:268 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP-ENV:Reason complex type: */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of XSD type xsd:string */
};
#endif
#endif

/* wsa.h:273 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of XSD type xsd:QName */
	char *faultstring;	/* optional element of XSD type xsd:string */
	char *faultactor;	/* optional element of XSD type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of XSD type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of XSD type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of XSD type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of XSD type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of XSD type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of XSD type SOAP-ENV:Detail */
};
#endif
#endif

/* wsdd10.h:57 */
#ifndef SOAP_TYPE_wsdd__HelloType
#define SOAP_TYPE_wsdd__HelloType (43)
/* wsdd:HelloType complex type: */
struct wsdd__HelloType
{
	struct wsa__EndpointReferenceType wsa__EndpointReference;	/* required element of XSD type wsa:EndpointReference */
	char *Types;	/* optional element of XSD type xsd:QName */
	struct wsdd__ScopesType *Scopes;	/* optional element of XSD type wsdd:ScopesType */
	char *XAddrs;	/* optional element of XSD type wsdd:UriListType */
	unsigned int MetadataVersion;	/* required element of XSD type xsd:unsignedInt */
};
#endif

/* wsdd10.h:60 */
#ifndef SOAP_TYPE_wsdd__ByeType
#define SOAP_TYPE_wsdd__ByeType (44)
/* wsdd:ByeType complex type: */
struct wsdd__ByeType
{
	struct wsa__EndpointReferenceType wsa__EndpointReference;	/* required element of XSD type wsa:EndpointReference */
	char *Types;	/* optional element of XSD type xsd:QName */
	struct wsdd__ScopesType *Scopes;	/* optional element of XSD type wsdd:ScopesType */
	char *XAddrs;	/* optional element of XSD type wsdd:UriListType */
	unsigned int *MetadataVersion;	/* optional element of XSD type xsd:unsignedInt */
};
#endif

/* wsdd10.h:63 */
#ifndef SOAP_TYPE_wsdd__ProbeType
#define SOAP_TYPE_wsdd__ProbeType (45)
/* wsdd:ProbeType complex type: */
struct wsdd__ProbeType
{
	char *Types;	/* optional element of XSD type xsd:QName */
	struct wsdd__ScopesType *Scopes;	/* optional element of XSD type wsdd:ScopesType */
};
#endif

/* wsdd10.h:66 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchesType
#define SOAP_TYPE_wsdd__ProbeMatchesType (46)
/* wsdd:ProbeMatchesType complex type: */
struct wsdd__ProbeMatchesType
{
	int __sizeProbeMatch;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <ProbeMatch> of XSD type wsdd:ProbeMatchType */
	struct wsdd__ProbeMatchType *ProbeMatch;
};
#endif

/* wsdd10.h:69 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchType
#define SOAP_TYPE_wsdd__ProbeMatchType (47)
/* wsdd:ProbeMatchType complex type: */
struct wsdd__ProbeMatchType
{
	struct wsa__EndpointReferenceType wsa__EndpointReference;	/* required element of XSD type wsa:EndpointReference */
	char *Types;	/* optional element of XSD type xsd:QName */
	struct wsdd__ScopesType *Scopes;	/* optional element of XSD type wsdd:ScopesType */
	char *XAddrs;	/* optional element of XSD type wsdd:UriListType */
	unsigned int MetadataVersion;	/* required element of XSD type xsd:unsignedInt */
};
#endif

/* wsdd10.h:72 */
#ifndef SOAP_TYPE_wsdd__ResolveType
#define SOAP_TYPE_wsdd__ResolveType (48)
/* wsdd:ResolveType complex type: */
struct wsdd__ResolveType
{
	struct wsa__EndpointReferenceType wsa__EndpointReference;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of XSD type wsa:EndpointReference */
};
#endif

/* wsdd10.h:75 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchesType
#define SOAP_TYPE_wsdd__ResolveMatchesType (49)
/* wsdd:ResolveMatchesType complex type: */
struct wsdd__ResolveMatchesType
{
	struct wsdd__ResolveMatchType *ResolveMatch;	/* optional element of XSD type wsdd:ResolveMatchType */
};
#endif

/* wsdd10.h:78 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchType
#define SOAP_TYPE_wsdd__ResolveMatchType (50)
/* wsdd:ResolveMatchType complex type: */
struct wsdd__ResolveMatchType
{
	struct wsa__EndpointReferenceType wsa__EndpointReference;	/* required element of XSD type wsa:EndpointReference */
	char *Types;	/* optional element of XSD type xsd:QName */
	struct wsdd__ScopesType *Scopes;	/* optional element of XSD type wsdd:ScopesType */
	char *XAddrs;	/* optional element of XSD type wsdd:UriListType */
	unsigned int MetadataVersion;	/* required element of XSD type xsd:unsignedInt */
};
#endif

/* wsdd10.h:84 */
#ifndef SOAP_TYPE_wsdd__SecurityType
#define SOAP_TYPE_wsdd__SecurityType (52)
/* wsdd:SecurityType complex type: */
struct wsdd__SecurityType
{
	struct wsdd__SigType *Sig;	/* optional element of XSD type wsdd:SigType */
};
#endif

/* wsdd10.h:87 */
#ifndef SOAP_TYPE_wsdd__SigType
#define SOAP_TYPE_wsdd__SigType (53)
/* wsdd:SigType complex type: */
struct wsdd__SigType
{
	char *Scheme;	/* required attribute of XSD type xsd:string */
	char *KeyId;	/* optional attribute of XSD type xsd:string */
	char *Refs;	/* required attribute of XSD type xsd:string */
	char *Sig;	/* required attribute of XSD type xsd:string */
};
#endif

/* wsdd10.h:81 */
#ifndef SOAP_TYPE_wsdd__ScopesType
#define SOAP_TYPE_wsdd__ScopesType (51)
/* wsdd:ScopesType simple type: */
struct wsdd__ScopesType
{
	char *__item;	/* mixed XML content */
	char *MatchBy;	/* optional attribute of XSD type xsd:string */
};
#endif

/* wsdd10.h:90 */
#ifndef SOAP_TYPE_wsdd__AppSequenceType
#define SOAP_TYPE_wsdd__AppSequenceType (54)
/* wsdd:AppSequenceType complex type: */
struct wsdd__AppSequenceType
{
	unsigned int InstanceId;	/* required attribute of XSD type xsd:unsignedInt */
	char *SequenceId;	/* optional attribute of XSD type xsd:string */
	unsigned int MessageNumber;	/* required attribute of XSD type xsd:unsignedInt */
};
#endif

/* wsdx.h:67 */
#ifndef SOAP_TYPE___wsdd__Hello
#define SOAP_TYPE___wsdd__Hello (67)
/* Operation wrapper: */
struct __wsdd__Hello
{
	struct wsdd__HelloType *wsdd__Hello;	/* optional element of XSD type wsdd:HelloType */
};
#endif

/* wsdx.h:76 */
#ifndef SOAP_TYPE___wsdd__Bye
#define SOAP_TYPE___wsdd__Bye (70)
/* Operation wrapper: */
struct __wsdd__Bye
{
	struct wsdd__ByeType *wsdd__Bye;	/* optional element of XSD type wsdd:ByeType */
};
#endif

/* wsdx.h:85 */
#ifndef SOAP_TYPE___wsdd__Probe
#define SOAP_TYPE___wsdd__Probe (73)
/* Operation wrapper: */
struct __wsdd__Probe
{
	struct wsdd__ProbeType *wsdd__Probe;	/* optional element of XSD type wsdd:ProbeType */
};
#endif

/* wsdx.h:94 */
#ifndef SOAP_TYPE___wsdd__ProbeMatches
#define SOAP_TYPE___wsdd__ProbeMatches (76)
/* Operation wrapper: */
struct __wsdd__ProbeMatches
{
	struct wsdd__ProbeMatchesType *wsdd__ProbeMatches;	/* optional element of XSD type wsdd:ProbeMatchesType */
};
#endif

/* wsdx.h:103 */
#ifndef SOAP_TYPE___wsdd__Resolve
#define SOAP_TYPE___wsdd__Resolve (79)
/* Operation wrapper: */
struct __wsdd__Resolve
{
	struct wsdd__ResolveType *wsdd__Resolve;	/* optional element of XSD type wsdd:ResolveType */
};
#endif

/* wsdx.h:112 */
#ifndef SOAP_TYPE___wsdd__ResolveMatches
#define SOAP_TYPE___wsdd__ResolveMatches (82)
/* Operation wrapper: */
struct __wsdd__ResolveMatches
{
	struct wsdd__ResolveMatchesType *wsdd__ResolveMatches;	/* optional element of XSD type wsdd:ResolveMatchesType */
};
#endif

/* onvif.h:294 */
#ifndef SOAP_TYPE___tdn__Hello
#define SOAP_TYPE___tdn__Hello (84)
/* Operation wrapper: */
struct __tdn__Hello
{
	struct wsdd__HelloType tdn__Hello;	/* required element of XSD type wsdd:HelloType */
};
#endif

/* onvif.h:348 */
#ifndef SOAP_TYPE___tdn__Bye
#define SOAP_TYPE___tdn__Bye (86)
/* Operation wrapper: */
struct __tdn__Bye
{
	struct wsdd__ByeType tdn__Bye;	/* required element of XSD type wsdd:ByeType */
};
#endif

/* onvif.h:402 */
#ifndef SOAP_TYPE___tdn__Probe
#define SOAP_TYPE___tdn__Probe (88)
/* Operation wrapper: */
struct __tdn__Probe
{
	struct wsdd__ProbeType tdn__Probe;	/* required element of XSD type wsdd:ProbeType */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* wsdd10.h:18 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* wsdd10.h:18 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/* wsa.h:220 */
#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
typedef struct wsa__EndpointReferenceType _wsa__EndpointReference;
#endif

/* wsa.h:223 */
#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
typedef char *_wsa__MessageID;
#endif

/* wsa.h:226 */
#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
typedef struct wsa__Relationship _wsa__RelatesTo;
#endif

/* wsa.h:229 */
#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
typedef char *_wsa__To;
#endif

/* wsa.h:232 */
#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
typedef char *_wsa__Action;
#endif

/* wsa.h:235 */
#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
typedef struct wsa__EndpointReferenceType _wsa__From;
#endif

/* wsa.h:238 */
#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
typedef struct wsa__EndpointReferenceType _wsa__ReplyTo;
#endif

/* wsa.h:241 */
#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
typedef struct wsa__EndpointReferenceType _wsa__FaultTo;
#endif

/* wsa.h:244 */
#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
typedef unsigned int _wsa__ReplyAfter;
#endif

/* wsdd10.h:101 */
#ifndef SOAP_TYPE_wsdd__QNameListType
#define SOAP_TYPE_wsdd__QNameListType (55)
typedef _QName wsdd__QNameListType;
#endif

/* wsdd10.h:104 */
#ifndef SOAP_TYPE_wsdd__UriListType
#define SOAP_TYPE_wsdd__UriListType (56)
typedef char *wsdd__UriListType;
#endif

/* wsdd10.h:107 */
#ifndef SOAP_TYPE_wsdd__FaultCodeOpenType
#define SOAP_TYPE_wsdd__FaultCodeOpenType (57)
typedef char *wsdd__FaultCodeOpenType;
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 SOAP_ENV__Fault(struct soap*, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Hello(struct soap*, struct wsdd__HelloType *wsdd__Hello);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Bye(struct soap*, struct wsdd__ByeType *wsdd__Bye);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Probe(struct soap*, struct wsdd__ProbeType *wsdd__Probe);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__ProbeMatches(struct soap*, struct wsdd__ProbeMatchesType *wsdd__ProbeMatches);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Resolve(struct soap*, struct wsdd__ResolveType *wsdd__Resolve);

SOAP_FMAC5 int SOAP_FMAC6 __wsdd__ResolveMatches(struct soap*, struct wsdd__ResolveMatchesType *wsdd__ResolveMatches);

SOAP_FMAC5 int SOAP_FMAC6 __tdn__Hello(struct soap*, struct wsdd__HelloType tdn__Hello, struct wsdd__ResolveType *tdn__HelloResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tdn__Bye(struct soap*, struct wsdd__ByeType tdn__Bye, struct wsdd__ResolveType *tdn__ByeResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tdn__Probe(struct soap*, struct wsdd__ProbeType tdn__Probe, struct wsdd__ProbeMatchesType *tdn__ProbeResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_SOAP_ENV__Fault(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Hello(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Bye(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Probe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__ProbeMatches(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Resolve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__ResolveMatches(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Hello(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Bye(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Probe(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_send_SOAP_ENV__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *_param_1);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__HelloType *wsdd__Hello);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Hello(struct soap *soap, struct __wsdd__Hello *_param_2);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ByeType *wsdd__Bye);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Bye(struct soap *soap, struct __wsdd__Bye *_param_3);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeType *wsdd__Probe);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Probe(struct soap *soap, struct __wsdd__Probe *_param_4);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__ProbeMatches(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeMatchesType *wsdd__ProbeMatches);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__ProbeMatches(struct soap *soap, struct __wsdd__ProbeMatches *_param_5);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Resolve(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ResolveType *wsdd__Resolve);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Resolve(struct soap *soap, struct __wsdd__Resolve *_param_6);


SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__ResolveMatches(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ResolveMatchesType *wsdd__ResolveMatches);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__ResolveMatches(struct soap *soap, struct __wsdd__ResolveMatches *_param_7);


SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__HelloType tdn__Hello, struct wsdd__ResolveType *tdn__HelloResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ByeType tdn__Bye, struct wsdd__ResolveType *tdn__ByeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeType tdn__Probe, struct wsdd__ProbeMatchesType *tdn__ProbeResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of discoverStub.h */
